### ISSUE TITLE
RabbitMQ not installed

### ISSUE THREAD

**Issue by MikeD096** [fluxlabs/baruwa#64]
Script references RabbitMQ v.3.5.3-1 (rabbitmq="3.5.3-1") and attempts to download it, but the wget line is incorrect as 3.5.3 is no longer the current version.

wget http://www.rabbitmq.com/releases/rabbitmq-server/current/rabbitmq-server-$rabbitmq.noarch.rpm
vs
wget http://www.rabbitmq.com/releases/rabbitmq-server/v3.5.3/rabbitmq-server-$rabbitmq.noarch.rpm

Please update to pull correct current version or change the wget to reference the 3.5.3 location.

**Comment by fluxlabs** [comment]
Bumped
